org.gradle.jvmargs=-Xmx3G -Djava.io.tmpdir=E:/StudioCamera/.toolchain/temp -Duser.home=E:/StudioCamera/.toolchain/user-home -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.java.installations.paths=E:/StudioCamera/.toolchain/jdk21
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
